name: PR - Build / Test (Next.js)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Disable Next.js telemetry
        run: echo "NEXT_TELEMETRY_DISABLED=1" >> $GITHUB_ENV

      - name: Build Next.js app
        run: npm run build # Build Next.js app

      - name: Run tests
        run: npm test # Run unit tests (Jest or Vitest)

      - name: Save build output
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: .next

      - name: Run tests
        run: npm test
