name: PR - Build / Test (Next.js)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd app && npm install --legacy-peer-deps

      # - name: Install dependencies
      #   run: npm install --legacy-peer-deps

      - name: Disable Next.js telemetry
        run: echo "NEXT_TELEMETRY_DISABLED=1" >> $GITHUB_ENV

      - name: Build Next.js app
        run: |
          cd app && npm run build

      - name: Run tests
        run: npm test # Run unit tests (Jest or Vitest)

      - name: Create test summary
        uses: test-summary/action@v2.4
        with:
          paths: ${{ github.workspace }}/results/*.xml
          output: ${{ github.workspace }}/results/summary.md
          show: "all"
        if: always()

      - name: Add Test Results To Job Summary
        run: |
          echo "TEST RESULTS:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat "${{ github.workspace }}/results/summary.md" >> $GITHUB_STEP_SUMMARY
        if: always()
        
        deploy:
        needs: build  # Only deploy if build succeeds
        runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
